
export const InvestmentData = [
  {
    id: 1,
    amount: 1000,
    term: 12,
    gain: 10,
    status: "completed",
    accepted: true,
    accepted_at: new Date(),
    date_of_refund: new Date(),
    refunded: false,
    refunded_at: new Date(),
    proof: "proof1",
    created_at: new Date(),
    updated_at: null,
    lender: 123,
    User: {
      id: 456,
      email: "user1@example.com",
      phone_number: "1234567890",
      full_name: "User 1",
      role: "user",
      password: "password1",
      deleted: false,
      email_verified: true,
      phone_number_verified: true,
      account_activated: true,
      created_at: new Date(),
      updated_at: null,
    },
    ChangeRequest: [
      {
        id: 789,
        amount: 500,
        treated: false,
        amount_to_refund: 250,
        refund_proof: null,
        created_at: new Date(),
        updated_at: null,
        investmentId: 1,
        lender: 123,
      },
      {
        id: 890,
        amount: 300,
        treated: true,
        amount_to_refund: 150,
        refund_proof: "proof2",
        created_at: new Date(),
        updated_at: null,
        investmentId: 1,
        lender: 123,
      },
    ],
  },
  {
    id: 2,
    amount: 2000,
    term: 24,
    gain: 20,
    status: "pending",
    accepted: false,
    accepted_at: null,
    date_of_refund: new Date(),
    refunded: false,
    refunded_at: new Date(),
    proof: "proof3",
    created_at: new Date(),
    updated_at: null,
    lender: 456,
    User: {
      id: 789,
      email: "user2@example.com",
      phone_number: "9876543210",
      full_name: null,
      role: "user",
      password: "password2",
      deleted: false,
      email_verified: true,
      phone_number_verified: true,
      account_activated: true,
      created_at: new Date(),
      updated_at: null,
    },
    ChangeRequest: [],
  },
];


export const usersData = [
    {
      id: 1,
      email: "user1@example.com",
      phone_number: "+22512345678",
      full_name: "John Doe",
      role: "lender",
      deleted: false,
      email_verified: true,
      phone_number_verified: true,
      account_activated: true,
      created_at: new Date(),
      updated_at: null,
    },
    {
      id: 2,
      email: "user2@example.com",
      phone_number: "+22598765432",
      full_name: "Jane Smith",
      role: "lender",
      deleted: false,
      email_verified: true,
      phone_number_verified: true,
      account_activated: true,
      created_at: new Date(),
      updated_at: null,
    },
    {
      id: 3,
      email: "user3@example.com",
      phone_number: "+22555555555",
      full_name: null,
      role: "moderator",
      deleted: true,
      email_verified: false,
      phone_number_verified: true,
      account_activated: false,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 4,
      email: "user4@example.com",
      phone_number: "+22544444444",
      full_name: "Mike Johnson",
      role: "customer advisor",
      deleted: false,
      email_verified: true,
      phone_number_verified: false,
      account_activated: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
  ];
  
  